$(document).ready(()=>{collectionsControl.setAddedToCategoryCollections();})
$(document).on("click",".open-collection-category-popover .action-button",(e)=>{window.openPopoverTime=Date.now();if($(e.currentTarget).parent().attr("not-logged-in")){return;}
var clipId=$(e.currentTarget).parent().attr("clip-id");var popoverTarget=$(e.currentTarget).parent();var data={csrf_token:csrf_token,clip_id:clipId};if($("#category-collection-popover").length>0){$("#category-collection-popover").fadeOut();return;}
$("#category-collection-popover").remove();cachedPopover=localStorage.getItem("cachedPopoverHtml");if(cachedPopover){window.collectionPopoverIsLoading=true;setTimeout(()=>{popoverHtml=cachedPopover;$(popoverTarget).append($(popoverHtml));var popover=$("#category-collection-popover");loaderHtml=`<div class="loader text-center"><i class="fa fa-spinner fa-spin"></i></div>`;$(popover).find(".available-categories").append(loaderHtml).addClass("loading");$(popover).attr("clip-id",clipId);$(".video-listing-item").css("z-index","initial");if($(popover).parents(".video-listing-item").length>0){$(popover).parents(".video-listing-item").css("z-index","99999");$(popover).parents(".video-listing-item").addClass("collection-popover-open");$("body").addClass("collection-popover-open");}
if($(popover).parents(".audio-player").length>0){$(popover).parents(".audio-player").css("z-index","99999");$(popover).parents(".audio-player").addClass("collection-popover-open");$("body").addClass("collection-popover-open");}
$(popover).fadeIn(50,()=>{if($(popover).css("position")=="fixed"){$("body").css("overflow","hidden");$("body").css("position","fixed");setTimeout(function(){$("body").css("position","initial");},10)}
loaderTopOffset=$(popover).find(".available-categories").height()/2;$(popover).find(".available-categories .loader").css("top",loaderTopOffset);});},1)
$.ajax({type:"GET",url:"/api/?path=user/get-all-collection-categories",data:data,success:function(resdata){timeSinceOpen=Date.now()-window.openPopoverTime;waitTimeout=300;if(timeSinceOpen<waitTimeout){waitTime=waitTimeout-timeSinceOpen;setTimeout(()=>{$("#category-collection-popover").find(".available-categories").removeClass("loading");$("#category-collection-popover .available-categories").html($(resdata).find(".available-categories").html());setTimeout(()=>{$("#category-collection-popover .available-categories").addClass("loaded");})},waitTime)}else{console.log("no wait: ",Date.now());$("#category-collection-popover").find(".available-categories").removeClass("loading");$("#category-collection-popover .available-categories").html($(resdata).find(".available-categories").html());setTimeout(()=>{$("#category-collection-popover .available-categories").addClass("loaded");})}},});}else{$.ajax({type:"GET",url:"/api/?path=user/get-all-collection-categories",data:data,success:function(res){try{error=JSON.parse(res);}catch{error=false;}
if(error){return;}
popoverHtml=res;$(popoverTarget).append(popoverHtml);var popover=$("#category-collection-popover");$(popover).attr("clip-id",clipId);$(".video-listing-item").css("z-index","initial");if($(popover).parents(".video-listing-item").length>0){$(popover).parents(".video-listing-item").css("z-index","99999");$(popover).parents(".video-listing-item").addClass("collection-popover-open");$("body").addClass("collection-popover-open");}
if($(popover).parents(".audio-player").length>0){$(popover).parents(".audio-player").css("z-index","99999");$(popover).parents(".audio-player").addClass("collection-popover-open");$("body").addClass("collection-popover-open");}
$("#category-collection-popover .available-categories").addClass("loaded");$(popover).fadeIn(10);setTimeout(()=>{if($(popover).css("position")=="fixed"){$("body").css("overflow","hidden");}},100)},});}})
$(window).on("scroll",()=>{$("#category-collection-popover").css("transition","none");})
$(document).on("click",".add-to-category-collection",(e)=>{var categoryItem=e.currentTarget;var clipId=$(e.currentTarget).parents("#category-collection-popover").attr("clip-id");if($("#category-collection-popover .actions-bar").is(":visible")){if($(categoryItem).children(".category-checkbox").hasClass("added")){$(categoryItem).children(".category-checkbox").removeClass("added");$(categoryItem).removeClass("added");}else{$(categoryItem).children(".category-checkbox").addClass("added");$(categoryItem).addClass("added");}
$("#category-collection-popover").addClass("dirty");return;}
var categoryId=$(e.currentTarget).attr("category-id");if($(categoryItem).children(".category-checkbox").hasClass("added")){collectionsControl.removeFromCategoryCollection(clipId,categoryId,(response)=>{if(response==true){$(categoryItem).children(".category-checkbox").removeClass("added");setTimeout(()=>{if($(categoryItem).parents(".open-collection-category-popover").find(".category-checkbox.added").length==0){$(categoryItem).parents(".open-collection-category-popover").removeClass("added");}
collectionsControl.showCollectionActionToastr("removed");collectionsControl.closeCollectionPopover();},400)}});}else{collectionsControl.addToCategoryCollection(clipId,categoryId,(response)=>{if(response==true){$(categoryItem).children(".category-checkbox").addClass("added");setTimeout(()=>{$(categoryItem).parents(".open-collection-category-popover").addClass("added");collectionsControl.showCollectionActionToastr("added");collectionsControl.closeCollectionPopover();},400)}});}}).on("click","#category-collection-popover .create-new-category-wrapper .before-create",(e)=>{$(e.currentTarget).parent().children(".create").css("display","flex");document.getElementById("new-category-name").focus({preventScroll:false});$(e.currentTarget).hide();}).on("click","#category-collection-popover .add-and-create-category",(e)=>{var clipId=$(e.currentTarget).parents("#category-collection-popover").attr("clip-id");var newCategoryName=$(e.currentTarget).parent().children("input").val();$(e.currentTarget).addClass("active");var currentTarget=e.currentTarget;if(!newCategoryName){alert("You must provide category name");return;}
collectionsControl.addAndCreateCategory(newCategoryName,clipId,(response)=>{if(response==true){$("#category-collection-popover").parents(".open-collection-category-popover").addClass("added");newCategoryHtml=$("#category-collection-popover .available-categories .add-to-category-collection")[0].outerHTML;$("#category-collection-popover .available-categories").prepend(newCategoryHtml);$("#category-collection-popover .available-categories .add-to-category-collection:first-child").css("opacity","0");$("#category-collection-popover .available-categories .add-to-category-collection:first-child").css("transition","0.3s");$("#category-collection-popover .available-categories .add-to-category-collection:first-child > span").text(newCategoryName);setTimeout(()=>{$("#category-collection-popover .available-categories .add-to-category-collection:first-child").css("opacity","1");$("#category-collection-popover .available-categories .add-to-category-collection:first-child").addClass("added");$("#category-collection-popover .available-categories .add-to-category-collection:first-child .category-checkbox").addClass("added");setTimeout(()=>{collectionsControl.closeCollectionPopover();$(currentTarget).parents(".open-collection-category-popover").addClass("added");collectionsControl.showCollectionActionToastr("added");},700)},200)}});}).on("click","#category-collection-popover .apply-selections",(e)=>{var clipId=$(e.currentTarget).parents("#category-collection-popover").attr("clip-id");var categories=[];$.each($(".add-to-category-collection.added"),(k,v)=>{categories.push($(v).attr("category-id"));})
var currentTarget=e.currentTarget;if(!$("#category-collection-popover").hasClass("dirty")){collectionsControl.closeCollectionPopover();return;}
collectionsControl.addClipToMultipleCollections(clipId,categories,(response)=>{if(response==true){if(categories.length==0){$(currentTarget).parents(".open-collection-category-popover").removeClass("added");collectionsControl.showCollectionActionToastr("removed");}else{$(currentTarget).parents(".open-collection-category-popover").addClass("added");collectionsControl.showCollectionActionToastr("added");}
collectionsControl.closeCollectionPopover();}});}).on("click","#category-collection-popover .clear-selections",(e)=>{collectionsControl.closeCollectionPopover();}).on("keydown","#new-category-name",(e)=>{if(e.keyCode==13&&$("#new-category-name").is(":focus")){e.preventDefault();$("#new-category-name").next().trigger("click");}})
$(document).on("click",".improved-collection-page .open-edit-collection-category-modal",(e)=>{}).on("click",".edit-collection-category-modal .close-edit-collection",()=>{}).on("click",".edit-collection-category-modal .cancel-delete",()=>{$(".edit-collection-category-modal-wrapper .edit-collection-category-modal").find(".before-delete-section").slideDown();$(".edit-collection-category-modal-wrapper .edit-collection-category-modal").find(".confirm-delete-section").slideUp();}).on("click",".edit-collection-category-modal .confirm-delete-collection",(e)=>{categoryId=$(e.target).parents(".edit-collection-category-modal").attr("category-id");collectionsControl.deleteCollection(categoryId,()=>{baseUrl=window.location.href.split("?")[0];window.location.href=baseUrl;});}).on("click",".edit-collection-category-modal .delete-collection",(e)=>{$(e.target).parents(".edit-collection-category-modal").find(".before-delete-section").slideUp();$(e.target).parents(".edit-collection-category-modal").find(".confirm-delete-section").slideDown();}).on("click",".edit-collection-category-modal .save-collection",(e)=>{categoryId=$(e.target).parents(".edit-collection-category-modal").attr("category-id");categoryName=$(e.target).parents(".edit-collection-category-modal").find("input[name='collection-name']").val();if(!categoryName){return;}
collectionsControl.saveCollectionDetails(categoryId,categoryName,(response)=>{$(".improved-collection-page .section-header h1").text(categoryName);$(".edit-collection-category-modal-wrapper").removeClass("open");$(".edit-collection-category-modal-wrapper").fadeOut();});})
var collectionsControl={addToCategoryCollection:(clipId,categoryId,callback)=>{if(!categoryId){categoryId=0;}
var params={"video_id":clipId,"category_id":categoryId,"csrf_token":csrf_token,}
$.ajax({url:'/api/?path=user/addToCategoryCollection&params='+JSON.stringify(params)}).done(function(data){if(data.success=true){callback(true);}else if(data.message=='Unauthorized'){callback(false);}})},addClipToMultipleCollections:(clipId,categories,callback)=>{var params={"video_id":clipId,"categories":categories,"csrf_token":csrf_token,}
$.ajax({url:'/api/?path=user/addClipToMultipleCollections&params='+JSON.stringify(params)}).done(function(data){if(data.success=true){callback(true);}else if(data.message=='Unauthorized'){callback(false);}})},removeFromCategoryCollection:(clipId,categoryId,callback)=>{if(!categoryId){categoryId=0;}
var params={"video_id":clipId,"category_id":categoryId,"csrf_token":csrf_token,}
$.ajax({url:'/api/?path=user/removeFromCategoryCollection&params='+JSON.stringify(params)}).done(function(data){if(data.success=true){callback(true);}else if(data.message=='Unauthorized'){callback(false);}})},setAddedToCategoryCollections:()=>{$.ajax({type:"GET",url:`/api/?path=user/get-clips-added-to-category-collection&csrf_token=${csrf_token}`,success:function(data){$.each($("[category-collection]"),function(key,el){clipId=parseFloat($(el).attr("clip-id"));try{a=JSON.parse(data);}catch(e){if(data){if(data[clipId]){$(el).addClass("added")}}}
$(el).removeClass("lazyload")})},});},addAndCreateCategory:(newCategoryName,clipId,callback)=>{var params={"video_id":clipId,"category_name":newCategoryName,"csrf_token":csrf_token,}
$.ajax({type:"POST",data:params,url:'/api/?path=user/addAndCreateCategory'}).done(function(data){if(data.success=true){callback(true);}else if(data.message=='Unauthorized'){callback(false);}})},deleteCollection:(categoryId,callback)=>{var params={"category_id":categoryId,"csrf_token":csrf_token,}
$.ajax({type:"POST",data:params,url:'/api/?path=user/deleteCollectionCategory'}).done(function(data){if(data.success=true){callback(true);}else if(data.message=='Unauthorized'){callback(false);}})},saveCollectionDetails:(categoryId,categoryName,callback)=>{var params={"category_id":categoryId,"category_name":categoryName,"csrf_token":csrf_token,}
$.ajax({type:"POST",data:params,url:'/api/?path=user/saveCollectionCategoryDetails'}).done(function(data){if(data.success=true){callback(true);}else if(data.message=='Unauthorized'){callback(false);}})},showCollectionActionToastr:(type)=>{$(".category-collection-updated-toastr:not(.favourites)").appendTo("body");if(type=='added'){$(".category-collection-updated-toastr:not(.favourites) .removed-msg").remove();}else{$(".category-collection-updated-toastr:not(.favourites) .added-msg").remove();}
$(".category-collection-updated-toastr:not(.favourites)").removeClass("hidden");setTimeout(()=>{$("#category-collection-popover").hide();setTimeout(()=>{$("#category-collection-popover").remove();},300);$(".category-collection-updated-toastr:not(.favourites)").addClass("show");},300);window.collectionToastrTimeout=setTimeout(()=>{$(".category-collection-updated-toastr:not(.favourites)").removeClass("show");setTimeout(()=>{$(".category-collection-updated-toastr:not(.favourites)").remove();},300)},4000)},closeCollectionPopover:()=>{if($("#category-collection-popover").length>0){$("body").css("overflow","initial");collectionsControl.preloadPopover();$("#preview_player").remove();$("#category-collection-popover").css("display","none");if($("#category-collection-popover").css("position")=="fixed"){if($("#category-collection-popover").parents(".video-thumb-wrapper").length>0){topOffset=$("#category-collection-popover").parents(".video-thumb-wrapper").offset().top;$(window).scrollTop(topOffset);}
if($("#category-collection-popover").parents(".audio-player").length>0){topOffset=$("#category-collection-popover").parents(".audio-player").offset().top;$(window).scrollTop(topOffset);}}
$("#category-collection-popover").remove();$(".audio-player.collection-popover-open").removeClass("collection-popover-open");$(".video-listing-item.collection-popover-open").removeClass("collection-popover-open");$("body").removeClass("collection-popover-open");$("body").css("position","initial");}},preloadPopover:()=>{var data={clip_id:-1,csrf_token:csrf_token,};$.ajax({type:"GET",url:"/api/?path=user/get-all-collection-categories",data:data,success:function(response){try{error=JSON.parse(res);}catch{error=false;}
if(error){return;}
localStorage.setItem("cachedPopoverHtml",response);},});}}
$(document).ready(()=>{collectionsControl.preloadPopover();})
$(document).on("mouseover","img[hover-src]",(e)=>{let el=e.target;$(el).attr("initial-src",$(el).attr("src"))
$(el).attr("src",$(el).attr("hover-src"))}).on("mouseout","img[hover-src]",(e)=>{let el=e.target;$(el).attr("src",$(el).attr("initial-src"))})
$(document).on("click",(e)=>{if(($(e.target).attr("id")!=="category-collection-popover")&&($(e.target).parents("#category-collection-popover").length==0)||$(e.target).hasClass("close-collection-popover")){if($("#category-collection-popover").length>0){collectionsControl.closeCollectionPopover();}
window.clearTimeout(window.collectionToastrTimeout);$(".category-collection-updated-toastr:not(.favourites)").remove();$(".audio-player").css("z-index","initial");$(".video-listing-item").css("z-index","initial");}})
$(document).on("click",".improved-collection-page .create-new-category-wrapper .before-create",(e)=>{$(e.target).hide();$(e.target).parents(".create-new-category-wrapper").children(".create").css("display","flex");$("#new-category-name").trigger("click");document.getElementById("new-category-name").focus({preventScroll:false});setTimeout(()=>{$("#new-category-name").trigger("click");document.getElementById("new-category-name").focus({preventScroll:false});},50)}).on("click",".improved-collection-page .collection-create-category",(e)=>{var newCategoryName=$(e.target).parent(".create").children("input").val();$(e.target).parent(".create").children("input").val("");$(e.target).addClass("active");if(!newCategoryName){return;}
params={"categoryName":newCategoryName,"csrf_token":csrf_token,}
$.ajax({type:"POST",data:params,url:'/api/?path=user/createCollectionCategory'}).done(function(data){if(data.success=true){$.ajax({type:"POST",data:params,url:'#'}).done(function(response){$(".list-categories-wrapper").prepend($(response).find(".list-categories-wrapper .collection-item:first-child")[0].outerHTML)
$(".list-categories-wrapper .collection-item:first-child").fadeOut();setTimeout(()=>{$(".list-categories-wrapper .collection-item:first-child").fadeIn();},200);})}})})
$(document).on("click",".collection-filter-trigger",(e)=>{$(".collection-filter-wrapper .dropdown-wrapper").hide();$(e.currentTarget).find(".dropdown-wrapper").show();}).on("click",(e)=>{if(!$(e.target).hasClass("collection-filter-trigger")&&$(e.target).parents(".collection-filter-trigger").length==0){$(".collection-filter-wrapper .dropdown-wrapper").hide();}})
$(document).on("mouseover","[collection-tooltip]",(e)=>{if($("#category-collection-popover").length>0){return;}
element=e.currentTarget;var tooltipText=$(element).attr("collection-tooltip");var collectionTooltipHtml=`<span style="display:none" id="collection-tooltip-html">${tooltipText}</span>`;$("body").append(collectionTooltipHtml);var translateX=-($("#collection-tooltip-html").width()*0.86-($(element).width()/2));$("#collection-tooltip-html").css("top",$(element).offset().top-$(window).scrollTop());$("#collection-tooltip-html").css("left",$(element).offset().left);$("#collection-tooltip-html").css("transform",`translateX(${translateX}px) translateY(calc(-100% - 10px))`);console.log(translateX);setTimeout(()=>{$("#collection-tooltip-html").fadeIn();})}).on("mouseout","[collection-tooltip]",(e)=>{$("#collection-tooltip-html").remove();}).on("mousemove scroll click",(e)=>{if($(e.target).parents("[collection-tooltip]").length==0&&!$(e.target).attr("collection-tooltip")){$("#collection-tooltip-html").remove();}
if(e.type=="click"){$("#collection-tooltip-html").remove();}})
$(document).ready(()=>{if($("body").hasClass("page-template-my-collection")){collectionFilters.init();}}).on("click","[collection-filter]",(e)=>{el=e.target;name=$(el).attr("data-name")
value=$(el).attr("data-value")
if(name=="license"||name=="sort"){window.currentCollectionFilters[name]=[value];if($(".collection-filters-wrapper.mobile-filters").is(":visible")){$("[collection-filter][data-name='"+name+"']").removeClass("option-selected");$(el).addClass("option-selected");collectionFilters.applyCurrentFilters(true);}else{collectionFilters.applyCurrentFilters();return;}}
if(name=="clip_type"){if(value=="show_all"){$("[collection-filter][data-name='clip_type']:not([data-value='show_all'])").removeClass("option-checked");}else{$("[collection-filter][data-name='clip_type'][data-value='show_all']").removeClass("option-checked");}
$(el).toggleClass("option-checked")}}).on("click",".collection-filter-wrapper .actions .clear-filters",(e)=>{$("[data-name='clip_type']").removeClass("option-checked");$(e.target).parents(".collection-filter-wrapper").find("[data-name='clip_type'][data-value='show_all']").addClass("option-checked");}).on("click",".collection-filter-wrapper .actions .apply-filters",(e)=>{selectedClipTypes=$(e.target).parents(".collection-filters-wrapper").find("[collection-filter][data-name='clip_type'].option-checked");filters=[];window.currentCollectionFilters["clip_type"]=[];$.each(selectedClipTypes,(k,v)=>{clipTypeValue=$(v).attr("data-value");if(clipTypeValue!="show_all"){window.currentCollectionFilters["clip_type"].push(clipTypeValue);}})
collectionFilters.applyCurrentFilters();}).on("click",".improved-collection-page .open-mobile-filters",(e)=>{$(".improved-collection-page .mobile-filter-content").show()
$("body").css("overflow","hidden")
if($(".mobile-filter-content").css("position")=="fixed"&&($(".mobile-filter-content").width()>$(window).width()/2)){$("body").css("position","fixed")}}).on("click",".improved-collection-page .close-collection-mobile-filter",(e)=>{if($(".mobile-filter-content").css("position")=="fixed"&&($(".mobile-filter-content").width()>$(window).width()/2)){$("body").css("position","initial")}
$(".improved-collection-page .mobile-filter-content").hide()
$("body").css("overflow","initial")}).on("click",".improved-collection-page .collection-index-open-sort-mobile",(e)=>{setTimeout(()=>{$(e.target).parents("#user-collection").find("#sort .dropdown-wrapper").toggle();})})
collectionFilters={init:()=>{collectionFilters.getCurrentFiltersAndCategory();$(".single-category-filters").css("opacity","1").css("height","initial");},getCurrentFiltersAndCategory:()=>{params=window.location.search.substr(1);params=params.split("&");if(params[0]==""){return}
assocParams=[];$.each(params,(k,v)=>{key=v.split("=")[0];values=v.split("=")[1].split(",");assocParams[key]=values;})
if(!assocParams["sort"]){assocParams["sort"]=[]}
if(!assocParams["license"]){assocParams["license"]=[]}
if(!assocParams["clip_type"]){assocParams["clip_type"]=[]}
window.currentCollectionFilters=assocParams;},applyCurrentFilters:(preventRedirect)=>{baseUrl=window.location.href.split("?")[0];stringifiedParams="?";params=[];Object.entries(window.currentCollectionFilters).forEach(entry=>{const[key,value]=entry;string=`${key}=${value.join(",")}`;if(value.length>0){if(value[0]!=""){params.push(string);}}});stringifiedParams+=params.join("&");if(!preventRedirect){window.location.href=baseUrl+stringifiedParams;}}}
$(document).ready(()=>{if($("body.page-template-my-favourites").length>0||$("body.page-template-my-collection").length>0){$("#user-collection").removeClass("hidden");}})